import { Transaction } from "../components/TransactionCard";

const blob = "https://qxjcpjrbfbjxwtjd.public.blob.vercel-storage.com/transactions";

export const transactions: Transaction[] = [
  {
    company: "M.O.M",
    sector: "Consumer",
    round: "Maiden institutional",
    investors: "IvyCap Ventures and Dexter Ventures",
    year: "Dec 2025",
    amount: "INR 52 cr",
    logo: `${blob}/MOM.png`,
  },
  {
    company: "Trufrost & Butler",
    sector: "Manufacturing",
    round: "Maiden institutional",
    investors: "Carpediem Capital and Dexter Capital",
    year: "Sept 2025",
    amount: "$ 7 mn",
    logo: `${blob}/Trufrost%20%26%20Butler.png`,
  },
  {
    company: "Khetika",
    sector: "Consumer",
    round: "Series B",
    investors: "Narottam Sekhsaria Family Office with participation from Anicut Capital",
    year: "Jul 2025",
    amount: "$18 mn",
    logo: `${blob}/Khetika.png`,
  },
  {
    company: "Mufin Green Finance",
    sector: "EV",
    round: "Debt Investment by",
    investors: "US-based DFI",
    year: "May 2025",
    amount: "$18mn",
    logo: `${blob}/Mufin.png`,
  },
  {
    company: "Miraggio",
    sector: "Consumer",
    round: "Series A",
    investors: "RPSG Capital Ventures, Client Associates, Prath",
    year: "May 2025",
    amount: "$6.5 mn",
    logo: `${blob}/Miraggio.png`,
  },
  {
    company: "JewelBox",
    sector: "Consumer",
    round: "Maiden institutional",
    investors: "V3 Ventures, JITO, Atrium Angels, Dexter Ventures, Infinyte",
    year: "Apr 2025",
    amount: "$3.2 mn",
    logo: `${blob}/JewelBox.png`,
  },
  {
    company: "Easebuzz",
    sector: "FinTech",
    round: "Series A",
    investors: "Bessemer Venture Partners, 8i, Varanium",
    year: "Apr 2025",
    amount: "$30 mn",
    logo: `${blob}/Easebuzz.png`,
  },
  {
    company: "The Bear House",
    sector: "Consumer",
    round: "Maiden institutional",
    investors: "JM Financial, Dexter Ventures",
    year: "Mar 2025",
    amount: "INR 50 cr",
    logo: `${blob}/The%20Bear%20House.png`,
  },
  {
    company: "RAS",
    sector: "Consumer",
    round: "Series A",
    investors: "Unilever, Amazon Smbhav",
    year: "Jan 2025",
    amount: "$5 mn",
    logo: `${blob}/RAS.png`,
  },
  {
    company: "Beyond Appliances",
    sector: "Consumer",
    round: "Maiden institutional",
    investors: "Fireside Ventures, Dharana Capital and multiple HNIs",
    year: "Nov 2024",
    amount: "$2mn",
    logo: `${blob}/Beyond%20Appliances.png`,
  },
  {
    company: "Basic Home Loans",
    sector: "FinTech",
    round: "Series B",
    investors: "Ashish Kacholia, Bertelsman India Investments, Crescent Enterprises Ventures",
    year: "Oct 2024",
    amount: "$10.6mn",
    logo: `${blob}/Basic%20Home%20Loans.png`,
  },
  {
    company: "Samvriddhi Inclusive Growth Network",
    sector: "Financial Services",
    round: "Sale to",
    investors: "MOS Utility",
    year: "Sep 2024",
    amount: "",
    logo: `${blob}/Samvriddhi.png`,
  },
  {
    company: "OPA",
    sector: "Marketing tech",
    round: "Acquisition",
    investors: "By Wondrlab",
    year: "Sep 2024",
    amount: "",
    logo: `${blob}/OPA.png`,
  },
  {
    company: "Nutrabay",
    sector: "Consumer",
    round: "Series A",
    investors: "RPSG Capital Ventures, Kotak Private Equity",
    year: "Sep 2024",
    amount: "$5mn",
    logo: `${blob}/Nutrabay.png`,
  },
  {
    company: "Supermoney",
    sector: "FinTech",
    round: "Investment by",
    investors: "Capria, Capital 2B",
    year: "June 2024",
    amount: "",
    logo: `${blob}/Supermoney.png`,
  },
  {
    company: "The Pant Project",
    sector: "Consumer",
    round: "Series A",
    investors: "Sorin, MGA Ventures, Dexter Ventures",
    year: "June 2024",
    amount: "$4.25 mn",
    logo: `${blob}/The%20Pant%20Project.png`,
  },
  {
    company: "OTP Less",
    sector: "SaaS",
    round: "Investment by",
    investors: "SIDBI Venture, Piper Serica, VH",
    year: "May 2024",
    amount: "",
    logo: `${blob}/OTP%20Less.png`,
  },
  {
    company: "FruBon",
    sector: "Consumer",
    round: "Investment by",
    investors: "Fireside Ventures, NDFO",
    year: "Dec 2023",
    amount: "",
    logo: `${blob}/FruBon.png`,
  },
  {
    company: "Hair Originals",
    sector: "Consumer",
    round: "Pre Series A",
    investors: "Anicut, Kesh Kala, and others",
    year: "Jan 2023",
    amount: "$1.25 mn",
    logo: `${blob}/Hair%20Originals.png`,
  },
  {
    company: "Blacklight",
    sector: "Consumer",
    round: "Maiden institutional",
    investors: "Dexter Ventures, Udyat, Kratos Studios",
    year: "Nov 2023",
    amount: "Undisclosed",
    logo: `${blob}/Blacklight.png`,
  },
  {
    company: "Inc 5",
    sector: "Consumer",
    round: "Series A",
    investors: "Carpediem, Param",
    year: "Oct 2023",
    amount: "$10mn",
    logo: `${blob}/Inc%205.png`,
  },
  {
    company: "Freakins",
    sector: "Consumer",
    round: "Not mentioned",
    investors: "Matrix Partners, Blume Ventures, Dexter Angels, marquee angels",
    year: "Jul 2023",
    amount: "$4mn",
    logo: `${blob}/Freakins.png`,
  },
  {
    company: "DeHaat",
    sector: "Agritech",
    round: "Series A",
    investors: "Sequoia Capital India, with co-investment from Dutch development bank FMO",
    year: "Apr 2023",
    amount: "$12mn",
    logo: `${blob}/DeHaat.png`,
  },
  {
    company: "ekincare",
    sector: "Consumer",
    round: "Series B",
    investors: "HealthQuad and Sabre Partners along with participation from existing investors Ventureast, Eight Roads Ventures, Siana Capital, and Endiya Partners",
    year: "Jan 2023",
    amount: "$15mn",
    logo: `${blob}/ekincare.png`,
  },
  {
    company: "Prozo",
    sector: "Logistics",
    round: "Series A",
    investors: "Sixth Sense and Jafco Asia",
    year: "Mar 2022",
    amount: "$10 mn",
    logo: `${blob}/Prozo.png`,
  },
  {
    company: "Sleepy Owl Coffee",
    sector: "Consumer",
    round: "Series A",
    investors: "Rukam Capital and DSG Consumer Partners",
    year: "Mar 2022",
    amount: "$6.5mn",
    logo: `${blob}/Sleepy%20Owl%20Coffee.png`,
  },
  {
    company: "DeHaat",
    sector: "Agritech",
    round: "Series D",
    investors: "Belgium-based investment firm Sofina and Lightrock India. Temasek co-invested in the round, with participation from existing investors Prosus, RTP Global, Sequoia Capital India, and FMO.",
    year: "Oct 2021",
    amount: "$115mn",
    logo: `${blob}/DeHaat.png`,
  },
  {
    company: "Gobbly",
    sector: "Consumer",
    round: "Pre Series A",
    investors: "Anicut Angel Fund and Sauce.VC",
    year: "Sep 2021",
    amount: "INR 7.2cr",
    logo: `${blob}/Gobbly.png`,
  },
  {
    company: "Pickrr",
    sector: "Logistics",
    round: "Series B",
    investors: "IIFL, Amicus Capital and Ananta Capital",
    year: "Aug 2021",
    amount: "$12mn",
    logo: `${blob}/pickrr.png`,
  },
  {
    company: "Pilgrim",
    sector: "Consumer",
    round: "Series A",
    investors: "Fireside Ventures and Rukam Capital",
    year: "Jun 2021",
    amount: "INR 13 cr",
    logo: `${blob}/Pilgrim.png`,
  },
  {
    company: "NIC",
    sector: "Consumer",
    round: "Not mentioned",
    investors: "JM Financial PE Fund",
    year: "Jun 2021",
    amount: "INR 35 cr",
    logo: `${blob}/NIC.png`,
  },
  {
    company: "WiT-ACE",
    sector: "Social/tech",
    round: "Seed round",
    investors: "Founders of CitiusTech and other prominent Angel investors",
    year: "Apr 2021",
    amount: "$1mn",
    logo: `${blob}/WiT-ACE.png`,
  },
  {
    company: "Pickrr",
    sector: "Logistics",
    round: "First institutional",
    investors: "Guild Capital and Omidyar Network India",
    year: "Dec 2020",
    amount: "$4mn",
    logo: `${blob}/pickrr.png`,
  },
  {
    company: "Arata",
    sector: "Consumer",
    round: "Pre Series A",
    investors: "Sixth Sense Ventures, Sequoia Capital India, with co-investment from Dutch development bank FMO",
    year: "Nov 2020",
    amount: "$1mn",
    logo: `${blob}/Arata.png`,
  },
  {
    company: "3rd Flix",
    sector: "Edtech",
    round: "Not mentioned",
    investors: "Exfinity Venture Partners, YourNest and IDFC Parampara",
    year: "Sep 2019",
    amount: "$3mn",
    logo: `${blob}/3rd%20Flix.png`,
  },
  {
    company: "DeHaat",
    sector: "Agritech",
    round: "Not mentioned",
    investors: "Omnivore Partners, AgFunder and a Family Office",
    year: "Mar 2019",
    amount: "$4mn",
    logo: `${blob}/DeHaat.png`,
  },
  {
    company: "FlipSpaces",
    sector: "Consumer",
    round: "Not mentioned",
    investors: "Carpediem Capital",
    year: "Jan 2019",
    amount: "$3.5mn",
    logo: `${blob}/FlipSpaces.png`,
  },
  {
    company: "Sheroes",
    sector: "Social media",
    round: "Not mentioned",
    investors: "Leo Capital, angel investors including Anand Chandrasekaran and its existing investors including Lumis Partners, Quintillion Media and the Withya HR Fund",
    year: "Sep 2018",
    amount: "Undisclosed",
    logo: `${blob}/Sheroes.png`,
  },
  {
    company: "LifCare",
    sector: "Health",
    round: "Series B",
    investors: "IL&FS, Nexus Venture Partners and SAIF Partners",
    year: "Jul 2018",
    amount: "$11mn",
    logo: `${blob}/LifCare.png`,
  },
  {
    company: "WholeSale Box",
    sector: "Consumer",
    round: "Not mentioned",
    investors: "RVCF (Rajasthan Venture Capital Fund)",
    year: "Jul 2018",
    amount: "Undisclosed",
    logo: `${blob}/WholeSale%20Box.png`,
  },
  {
    company: "MobiQuest",
    sector: "SaaS",
    round: "Strategic investment",
    investors: "Paytm",
    year: "Jul 2018",
    amount: "",
    logo: `${blob}/MobiQuest.png`,
  },
  {
    company: "ACE tractor JV",
    sector: "Agri",
    round: "JV",
    investors: "NA",
    year: "Apr 2018",
    amount: "",
    logo: `${blob}/ACE%20tractor%20JV.png`,
  },
  {
    company: "QualTouch",
    sector: "BPO",
    round: "Merger with Mas Callnet",
    investors: "NA",
    year: "Aug 2017",
    amount: "",
    logo: `${blob}/QualTouch.png`,
  },
  {
    company: "Data Resolve",
    sector: "Cybersecurity",
    round: "Not mentioned",
    investors: "Parampara Capital's IDFC - Parampara Fund",
    year: "Mar 2017",
    amount: "$1mn",
    logo: `${blob}/Data%20Resolve.png`,
  },
  {
    company: "Wholesale Box",
    sector: "Consumer",
    round: "Not mentioned",
    investors: "institutional investors and marquee angel investors including Manish Maheshwari, CEO of Network 18 Digital and Contrarian Vriddhi Fund",
    year: "Nov 2016",
    amount: "$2mn",
    logo: `${blob}/WholeSale%20Box.png`,
  },
  {
    company: "Goalwise",
    sector: "Fintech",
    round: "Not mentioned",
    investors: "Undisclosed HNIs",
    year: "May 2016",
    amount: "$1mn",
    logo: `${blob}/Goalwise.png`,
  },
  {
    company: "LifCare",
    sector: "Health",
    round: "Seed capital",
    investors: "Rajul Garg, Alok Mittal (ex-Cannan Partners), Rishi Mandawat (Bain Capital), Dheeraj Jain (Partner-Redcliffe Capital, London), Kunal Shah (CEO, FreeCharge), Sandeep Tandon (Co-founder, FreeCharge), Dexter Angel Circle and others",
    year: "Mar 2016",
    amount: "",
    logo: `${blob}/LifCare.png`,
  },
  {
    company: "Dogspot",
    sector: "Consumer",
    round: "Series A",
    investors: "Ratan Tata, Ronnie Screwvala, K Ganesh, India Quotient and Dexter Angel Circle",
    year: "Jan 2016",
    amount: "Undisclosed",
    logo: `${blob}/Dogspot.png`,
  },
  {
    company: "Bestdealfinance",
    sector: "Finance",
    round: "Series A",
    investors: "Kalaari Capital with participation from YourNest Angel Fund, Globevestor & Dexter Angel Circle",
    year: "Nov 2015",
    amount: "$3 mn",
    logo: `${blob}/Bestdealfinance.png`,
  },
];
